services:
  security-app:
    build: .
    container_name: security-dashboard
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ORG_NAME=${ORG_NAME:-Netflix}
      - REPO_LIMIT=${REPO_LIMIT:-5}
      - DAYS_ACTIVE=${DAYS_ACTIVE:-30}
      - SKIP_IF_RESULTS_EXIST=${SKIP_IF_RESULTS_EXIST:-1}
    command: /usr/local/bin/run_pipeline_and_jupyter.sh
